a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espacos?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?' ,a.isalnum())
print('Ésta em maiusculas?', a.isupper())
print('Ésta em miiusculas?', a.islower())
print('Ésta em capitalizada?', a.istitle())